from . import hr_contract_type
from . import hr_contract
from . import hr_employee
from . import hr_payroll_structure
from . import hr_salary_rule_category
from . import hr_salary_rule
from . import hr_salary_rule_account
from . import hr_employee_document
from . import hr_employee_movement
from . import hr_employee_movement_line
from . import hr_payslip
from . import hr_payslip_line
from . import hr_payslip_run
from . import hr_payslip_move
from . import hr_payslip_input
from . import account_move_line